name: Reddit to Instagram Bot

on:
  schedule:
    - cron: "30 19 * * *" # Cron expression for daily at 07:30pm UTC : 2:00am In IST
  workflow_dispatch: # Allows you to manually run the workflow

jobs:
  run-bot:
    runs-on: ubuntu-latest # Use a Linux environment

    steps:
      - name: Checkout code # Get your code
        uses: actions/checkout@v4

      - name: Set up Python # Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9 # Or your Python version

      - name: Install dependencies # Install your bot's libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot script # Run your Python script
        run: python main.py # Or whatever your script is called
